labels:
  type: exec
  platform: linux/amd64

steps:
- name: test-linux
  image: bash
  commands:
  - make bootstrap test
  - curl -s https://codecov.io/bash | bash
  environment:
    DEV_REGISTRY:
      from_secret: dev_registry
    CODECOV_TOKEN:
      from_secret: codecov_token
  when:
    event:
    - push
    - tag
